### ISSUE TITLE
FFL: Being able to individually change sponsor logos on the Credit page for each country

### ISSUE THREAD

**Issue by Botswang** [universalcore/unicore#113] opened 2014-11-17 08:27 UTC
### Is there clear value to clients/users (the grandma test)?

Yes, Unicef do not have the same sponsors for each country. 
### Have real-world users been consulted in designing the feature?

Yes, Unicef need to be able to credit to the right sponsors in each country
### Can it be measured?

No
### Can be shipped in 2-4 weeks?

Yes
### Has a mockup been created?

No
### Did we pivot?

No
### Is it coupled to a project?

Yes, FFL
### Is it bloggable/slackable/tweetable?

No
### Compound value, will it be used elsewhere?

Yes, it can be repurposed for other sites
### Has a partner or client be consulted, interviewed?

Yes, Unicef was the 'author' of this request

**Comment by smn** [comment] 2014-11-17 10:18
Duplicate of #112

**Closed as completed** 2014-11-17 10:18 UTC
Labels: duplicate
